const express = require("express");
const fs = require("fs/promises");
const path = require("path");
const crypto = require("crypto");
const { validateReview, reviewFingerprint, buildConsensus, reviewerStats } = require("./reviewer");
const { buildReliabilityReport } = require("./reliability-engine");
const { evaluateCertification } = require("./certification-engine");
const store = require("./storage-adapter");
const auth = require("./auth");
const gold = require("./gold");
const db = require("./db");
const reviewerControl = require("./reviewer-quality-control-db");
const buyerApi = require("./buyer-api");
const buyerManagement = require("./buyer-management");
const app = express();
const PORT = process.env.PORT || 8787;
const EXPORT_DIR = path.join(__dirname, "..", "exports");
const RELEASE_DIR = path.join(__dirname, "..", "releases");
const dimensions = ["accuracy", "relevance", "clarity", "safety"];
const DATASET_VERSION = "0.9.1";
app.use(express.json({ limit: "100kb" }));
app.use((req,res,next)=>{const origin=process.env.CORS_ORIGIN||"*";res.setHeader("Access-Control-Allow-Origin",origin);res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization, X-API-Key");res.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS");if(req.method==="OPTIONS")return res.sendStatus(204);next();});
function validate(body){const errors=[];if(!body.prompt||typeof body.prompt!=="string")errors.push("prompt is required");if(!body.response_a||typeof body.response_a!=="string")errors.push("response_a is required");if(!body.response_b||typeof body.response_b!=="string")errors.push("response_b is required");if(!["A","B","Tie"].includes(body.preferred_response))errors.push("preferred_response must be A, B, or Tie");if(!body.reason||body.reason.trim().length<10)errors.push("reason must contain at least ten characters");for(const d of dimensions)for(const s of ["a","b"]){const v=body[`${d}_${s}`];if(!Number.isInteger(v)||v<1||v>5)errors.push(`${d}_${s} must be an integer from 1 to 5`);}return errors;}
async function readExport(name){return JSON.parse(await fs.readFile(path.join(EXPORT_DIR,name),"utf8"));}
async function readRelease(version,name){if(!/^\d+\.\d+\.\d+$/.test(version))throw new Error("Invalid release version");return fs.readFile(path.join(RELEASE_DIR,`v${version}`,name),"utf8");}
function sendStorageError(res,error,fallback){console.error(error);if(error?.code==="23505")return res.status(409).json({error:"Duplicate record violates a database uniqueness rule"});if(error?.code==="23503")return res.status(400).json({error:"Referenced record does not exist"});return res.status(500).json({error:fallback});}
function requireAdmin(req,res,next){auth.requireAuth(req,res,()=>{if(req.auth.role!=="admin")return res.status(403).json({error:"Admin role required"});next();});}
app.get("/api/health",async(req,res)=>{try{if(store.mode()==="postgres")await db.query("SELECT 1");res.json({status:"ok",service:"modeljudge-api",version:DATASET_VERSION,storage:store.mode(),authentication:store.mode()==="postgres"?"enabled":"requires-postgres",gold_calibration:"enabled",reliability_reporting:"enabled",reviewer_quality_control:store.mode()==="postgres"?"enabled":"requires-postgres",buyer_api:store.mode()==="postgres"?"enabled":"requires-postgres",buyer_management:store.mode()==="postgres"?"enabled":"requires-postgres"});}catch{res.status(503).json({status:"error",service:"modeljudge-api",version:DATASET_VERSION,storage:store.mode()});}});
app.post("/api/auth/login",async(req,res)=>{const{reviewer_id,password}=req.body||{};if(typeof reviewer_id!=="string"||typeof password!=="string")return res.status(400).json({error:"reviewer_id and password are required"});try{const session=await auth.login(reviewer_id.trim(),password);if(!session)return res.status(401).json({error:"Invalid reviewer credentials"});res.json(session);}catch(error){return sendStorageError(res,error,"Unable to authenticate reviewer");}});
app.post("/api/auth/logout",auth.requireAuth,async(req,res)=>{try{await auth.revoke(auth.bearerToken(req));res.json({message:"Logged out"});}catch{res.status(500).json({error:"Unable to revoke session"});}});
app.get("/api/auth/me",auth.requireAuth,(req,res)=>res.json({reviewer_id:req.auth.reviewer_id,role:req.auth.role}));
app.post("/api/auth/accounts",async(req,res)=>{if(!db.isConfigured())return res.status(503).json({error:"Account creation requires PostgreSQL"});if(!process.env.ADMIN_BOOTSTRAP_TOKEN||req.get("x-admin-bootstrap-token")!==process.env.ADMIN_BOOTSTRAP_TOKEN)return res.status(403).json({error:"Admin bootstrap authorization required"});try{res.status(201).json(await auth.createAccount({reviewerId:req.body.reviewer_id,password:req.body.password,role:req.body.role||"reviewer"}));}catch(error){return sendStorageError(res,error,"Unable to create reviewer account");}});
app.get("/api/gold/task",auth.requireAuth,async(req,res)=>{try{const task=await gold.getTask(req.auth.reviewer_id);if(!task)return res.status(503).json({error:"No calibration tasks configured"});res.json(task);}catch{res.status(503).json({error:"Calibration service unavailable"});}});
app.post("/api/gold/submit",auth.requireAuth,async(req,res)=>{const errors=gold.validateSubmission(req.body);if(errors.length)return res.status(400).json({error:"Calibration validation failed",errors});try{const result=await gold.submit({reviewerId:req.auth.reviewer_id,goldEvaluationId:req.body.gold_evaluation_id,preferredResponse:req.body.preferred_response});if(result.error)return res.status(result.status).json({error:result.error});const quality=await reviewerControl.refresh(req.auth.reviewer_id,req.auth.reviewer_id,"calibration_submission");res.json({...result,quality});}catch(error){return sendStorageError(res,error,"Unable to record calibration attempt");}});
app.get("/api/gold/me",auth.requireAuth,async(req,res)=>{try{res.json(await gold.reviewerQuality(req.auth.reviewer_id));}catch{res.status(503).json({error:"Unable to calculate calibration quality"});}});
app.get("/api/reviewers/me/quality",auth.requireAuth,async(req,res)=>{try{res.json(await reviewerControl.get(req.auth.reviewer_id));}catch(error){return sendStorageError(res,error,"Unable to read reviewer quality");}});
app.get("/api/reviewers/me/history",auth.requireAuth,async(req,res)=>{try{res.json({reviewer_id:req.auth.reviewer_id,history:await reviewerControl.history(req.auth.reviewer_id)});}catch(error){return sendStorageError(res,error,"Unable to read reviewer quality history");}});
app.get("/api/admin/reviewer-quality",requireAdmin,async(req,res)=>{try{const rows=await reviewerControl.list();res.json({reviewer_count:rows.length,reviewers:rows});}catch(error){return sendStorageError(res,error,"Unable to read reviewer quality controls");}});
app.post("/api/admin/reviewer-quality/:reviewerId/reinstate",requireAdmin,async(req,res)=>{try{res.json(await reviewerControl.adminSet(req.params.reviewerId,"active",req.auth.reviewer_id,req.body?.reason));}catch(error){return sendStorageError(res,error,"Unable to reinstate reviewer");}});
app.post("/api/admin/reviewer-quality/:reviewerId/suspend",requireAdmin,async(req,res)=>{try{res.json(await reviewerControl.adminSet(req.params.reviewerId,"suspended",req.auth.reviewer_id,req.body?.reason));}catch(error){return sendStorageError(res,error,"Unable to suspend reviewer");}});
app.get("/api/evaluations",async(req,res)=>{try{if(store.mode()==="postgres"){try{await store.syncApprovedReviews();}catch(error){console.error("[verification] request sync failed:",error);}}const limit=Math.min(Math.max(Number(req.query.limit)||50,1),500);res.json({count:await store.countEvaluations(),records:await store.listEvaluations(limit)});}catch{res.status(500).json({error:"Unable to read evaluations"});}});
app.post("/api/evaluations",async(req,res)=>{const errors=validate(req.body);if(errors.length)return res.status(400).json({error:"Validation failed",errors});try{const fingerprint=crypto.createHash("sha256").update([req.body.prompt,req.body.response_a,req.body.response_b].join("\n")).digest("hex");if(await store.evaluationFingerprintExists(fingerprint))return res.status(409).json({error:"Duplicate evaluation pair detected",fingerprint});const record={id:req.body.id||`MJ-${crypto.randomUUID()}`,prompt:req.body.prompt.trim(),response_a:req.body.response_a.trim(),response_b:req.body.response_b.trim(),preferred_response:req.body.preferred_response,...Object.fromEntries(dimensions.flatMap(d=>[[`${d}_a`,req.body[`${d}_a`]], [`${d}_b`,req.body[`${d}_b`]]])),preference_strength:req.body.preference_strength||"moderate",reason:req.body.reason.trim(),category:req.body.category||"General Knowledge",language:req.body.language||"en",verified:false,fingerprint,created_at:new Date().toISOString(),dataset_version:DATASET_VERSION};await store.insertEvaluation(record);res.status(201).json({message:"Evaluation saved",record});}catch(error){return sendStorageError(res,error,"Unable to save evaluation");}});
app.get("/api/reviews",async(req,res)=>{try{const reviews=await store.listReviews(req.query.evaluation_id);res.json({count:reviews.length,reviews});}catch{res.status(500).json({error:"Unable to read reviews"});}});
app.post("/api/reviews",auth.requireAuth,async(req,res)=>{const errors=validateReview(req.body);if(errors.length)return res.status(400).json({error:"Review validation failed",errors});try{if(req.body.reviewer_id&&req.body.reviewer_id!==req.auth.reviewer_id)return res.status(403).json({error:"reviewer_id does not match authenticated reviewer"});const control=await reviewerControl.get(req.auth.reviewer_id);if(control.status==="suspended")return res.status(403).json({error:"Reviewer is suspended",status:control.status,action:"recalibrate"});if(control.status==="insufficient")return res.status(403).json({error:"Reviewer calibration is insufficient",status:control.status,action:"calibrate"});if(control.status==="warning")res.setHeader("X-Reviewer-Quality-Warning","recalibration-recommended");if(!await store.findEvaluation(req.body.evaluation_id))return res.status(404).json({error:"Evaluation not found"});const reviews=await store.listReviews(req.body.evaluation_id);const reviewerId=req.auth.reviewer_id;const fingerprint=reviewFingerprint({...req.body,reviewer_id:reviewerId});if(await store.reviewFingerprintExists(fingerprint)||reviews.some(r=>r.reviewer_id===reviewerId))return res.status(409).json({error:"Reviewer already reviewed this evaluation"});const review={id:`REV-${crypto.randomUUID()}`,evaluation_id:req.body.evaluation_id,reviewer_id:reviewerId,submitted_by_account_id:req.auth.id,preferred_response:req.body.preferred_response,verification_action:req.body.verification_action||"pending",...Object.fromEntries(dimensions.flatMap(d=>[[`${d}_a`,req.body[`${d}_a`]], [`${d}_b`,req.body[`${d}_b`]]])),reason:req.body.reason.trim(),confidence:req.body.confidence||"medium",fingerprint,created_at:new Date().toISOString(),quality_flag:"pending"};await store.insertReview(review);const quality=await reviewerControl.refresh(reviewerId,reviewerId,"review_submission");res.status(201).json({message:"Review saved",review,quality,consensus:buildConsensus([...reviews,review])});}catch(error){return sendStorageError(res,error,"Unable to save review");}});
app.get("/api/reviews/consensus/:evaluationId",async(req,res)=>{try{const reviews=await store.listReviews(req.params.evaluationId);res.json({evaluation_id:req.params.evaluationId,...buildConsensus(reviews)});}catch{res.status(500).json({error:"Unable to calculate consensus"});}});
app.get("/api/reviewers/stats",async(req,res)=>{try{const rows=await store.reviewerStatsRows();if(rows)return res.json({reviewer_count:rows.length,reviewers:rows});const reviews=await store.listReviews();res.json({reviewer_count:new Set(reviews.map(r=>r.reviewer_id)).size,reviewers:reviewerStats(reviews)});}catch{res.status(500).json({error:"Unable to calculate reviewer statistics"});}});
app.get("/api/reliability",async(req,res)=>{try{res.json(buildReliabilityReport(await store.listEvaluations(5000),await store.listReviews()));}catch(error){console.error(error);res.status(503).json({error:"Reliability report unavailable"});}});
app.get("/api/certification",async(req,res)=>{try{const report=await readExport("certification-report.json");res.json(report);}catch{try{const release=await readExport("quality-report.json"), reliability=buildReliabilityReport(await store.listEvaluations(5000),await store.listReviews());const result=evaluateCertification({evaluations:release.record_count||0,reviewed_evaluations:reliability.sample.reviewed_evaluation_count||0,multi_reviewed_evaluations:reliability.sample.multi_reviewed_evaluation_count||0,average_quality_score:release.average_quality_score||0,review_coverage:reliability.sample.evaluation_count?(reliability.sample.review_count||0)/reliability.sample.evaluation_count:0,duplicate_rate:release.duplicate_rate||0,calibration_accuracy:0,reliability_sample:reliability.sample.multi_reviewed_evaluation_count||0});res.json({generated_at:new Date().toISOString(),status:result.status,certification:result,note:"Calibration evidence is unavailable until calibration records are generated."});}catch(error){return sendStorageError(res,error,"Certification report unavailable");}}});
app.get("/api/release",async(req,res)=>{try{const records=await store.listEvaluations(5000),recordCount=await store.countEvaluations(),uniquePrompts=new Set(records.map(r=>r.prompt).filter(Boolean)).size,fingerprints=new Set(records.map(r=>r.fingerprint).filter(Boolean)),verified=records.filter(r=>r.verified===true).length;let scoreTotal=0,scoreCount=0;for(const record of records)for(const key of ["accuracy_a","accuracy_b","relevance_a","relevance_b","clarity_a","clarity_b","safety_a","safety_b"]){const value=record[key];if(Number.isInteger(value)){scoreTotal+=value;scoreCount++;}}const averageQualityScore=scoreCount?Number((scoreTotal/scoreCount).toFixed(3)):0,humanVerificationRate=recordCount?Number((verified/recordCount).toFixed(4)):0,duplicateRate=recordCount?Number(((recordCount-fingerprints.size)/recordCount).toFixed(4)):0;res.json({version:DATASET_VERSION,dataset_name:"ModelJudge AI Human Preference Evaluations",format:"JSONL",record_count:recordCount,generated_at:new Date().toISOString(),average_quality_score:averageQualityScore,human_verification_rate:humanVerificationRate,unique_prompts:uniquePrompts,duplicate_rate:duplicateRate,schema:"data/schemas/evaluation.schema.json",quality_report:"live database metrics"});}catch(error){console.error("Release metadata error:",error);res.status(503).json({error:"Release API unavailable"});}});
app.get("/api/buyer/releases",buyerApi.requireScope("dataset:read"),async(req,res)=>{try{const entries=await fs.readdir(RELEASE_DIR,{withFileTypes:true});const versions=entries.filter(e=>e.isDirectory()&&/^v\d+\.\d+\.\d+$/.test(e.name)).map(e=>e.name.slice(1)).sort().reverse();res.json({dataset_name:"ModelJudge AI Human Preference Evaluations",versions});}catch(error){return sendStorageError(res,error,"Buyer release catalog unavailable");}});
app.get("/api/buyer/releases/:version/manifest",buyerApi.requireScope("dataset:read"),async(req,res)=>{try{res.type("json").send(await readRelease(req.params.version,"RELEASE-MANIFEST.json"));}catch{try{res.type("json").send(await readRelease(req.params.version,"manifest.json"));}catch{res.status(404).json({error:"Release not found"});}}});
app.get("/api/buyer/releases/:version/dataset",buyerApi.requireScope("dataset:read"),async(req,res)=>{const format=req.query.format==="csv"?"csv":"jsonl";const file=`evaluations.${format}`;try{const content=await readRelease(req.params.version,file);let manifest;try{manifest=JSON.parse(await readRelease(req.params.version,"RELEASE-MANIFEST.json"));}catch{manifest=JSON.parse(await readRelease(req.params.version,"manifest.json"));}await buyerApi.recordDownload({buyerId:req.buyer.buyer_id,apiKeyId:req.buyer.id,version:req.params.version,format,recordCount:manifest.record_count,ip:req.ip});res.setHeader("Content-Disposition",`attachment; filename="modeljudge-${req.params.version}.${format}"`);res.type(format==="csv"?"text/csv":"application/x-ndjson").send(content);}catch(error){console.error("Buyer release dataset error:",error);res.status(404).json({error:"Requested release or format not found"});}});
app.get("/api/buyer/releases/:version/quality",buyerApi.requireScope("dataset:read"),async(req,res)=>{try{res.type("json").send(await readRelease(req.params.version,"quality-report.json"));}catch{res.status(404).json({error:"Quality report not found"});}});
app.get("/api/buyer/usage",buyerApi.requireScope("dataset:read"),async(req,res)=>{try{res.json(await buyerManagement.usage(req.buyer.buyer_id));}catch(error){return sendStorageError(res,error,"Buyer usage unavailable");}});
app.get("/api/buyer/keys",buyerApi.requireScope("dataset:read"),async(req,res)=>{try{res.json({buyer_id:req.buyer.buyer_id,keys:await buyerManagement.listKeys(req.buyer.buyer_id)});}catch(error){return sendStorageError(res,error,"Unable to list buyer API keys");}});
app.post("/api/buyer/keys/:keyId/revoke",buyerApi.requireScope("dataset:read"),async(req,res)=>{try{const result=await buyerManagement.revokeKey(req.params.keyId,req.buyer.buyer_id);if(!result)return res.status(404).json({error:"API key not found"});res.json(result);}catch(error){return sendStorageError(res,error,"Unable to revoke API key");}});
app.post("/api/buyer/keys/:keyId/rotate",buyerApi.requireScope("dataset:read"),async(req,res)=>{try{const result=await buyerManagement.rotateKey(req.params.keyId,req.buyer.buyer_id,req.body?.name);if(!result)return res.status(404).json({error:"Active API key not found"});res.json(result);}catch(error){return sendStorageError(res,error,"Unable to rotate API key");}});
app.get("/api/admin/buyers",requireAdmin,async(req,res)=>{try{res.json({buyers:await buyerManagement.listBuyers()});}catch(error){return sendStorageError(res,error,"Unable to list buyers");}});
app.post("/api/admin/buyers",requireAdmin,async(req,res)=>{if(typeof req.body?.buyer_id!=="string"||typeof req.body?.company_name!=="string")return res.status(400).json({error:"buyer_id and company_name are required"});try{res.status(201).json(await buyerManagement.createBuyer(req.body));}catch(error){return sendStorageError(res,error,"Unable to create buyer");}});
app.get("/api/admin/buyers/:buyerId",requireAdmin,async(req,res)=>{try{const buyer=await buyerManagement.getBuyer(req.params.buyerId);if(!buyer)return res.status(404).json({error:"Buyer not found"});res.json({buyer,keys:await buyerManagement.listKeys(req.params.buyerId),usage:await buyerManagement.usage(req.params.buyerId)});}catch(error){return sendStorageError(res,error,"Unable to read buyer");}});
app.post("/api/admin/buyers/:buyerId/status",requireAdmin,async(req,res)=>{if(!["active","suspended","closed"].includes(req.body?.status))return res.status(400).json({error:"status must be active, suspended, or closed"});try{const buyer=await buyerManagement.setBuyerStatus(req.params.buyerId,req.body.status);if(!buyer)return res.status(404).json({error:"Buyer not found"});res.json(buyer);}catch(error){return sendStorageError(res,error,"Unable to update buyer status");}});
app.post("/api/admin/buyers/:buyerId/keys",requireAdmin,async(req,res)=>{try{const result=await buyerApi.createBuyerKey({buyerId:req.params.buyerId,name:req.body?.name,scopes:req.body?.scopes||["dataset:read"],dailyLimit:Number(req.body?.daily_limit)||1000});res.status(201).json(result);}catch(error){return sendStorageError(res,error,"Unable to create buyer API key");}});

async function logVerificationDiagnostic() {if(store.mode()!=="postgres")return;try{const reviews=await db.query(`SELECT COUNT(*)::int AS total,COUNT(*) FILTER (WHERE LOWER(COALESCE(verification_action,''))='approved')::int AS approved_action,COUNT(*) FILTER (WHERE LOWER(COALESCE(verification_action,''))='pending')::int AS pending_action,COUNT(*) FILTER (WHERE LOWER(COALESCE(verification_action,''))='revision requested')::int AS revision_requested_action,COUNT(*) FILTER (WHERE LOWER(COALESCE(verification_action,''))='rejected')::int AS rejected_action,COUNT(*) FILTER (WHERE LOWER(COALESCE(reason,'')) LIKE 'reviewer approved:%')::int AS approved_reason,COUNT(*) FILTER (WHERE LOWER(COALESCE(reason,'')) LIKE 'reviewer revision requested:%')::int AS revision_requested_reason,COUNT(*) FILTER (WHERE LOWER(COALESCE(reason,'')) LIKE 'reviewer rejected:%')::int AS rejected_reason FROM reviews`);const evaluations=await db.query(`SELECT COUNT(*)::int AS total,COUNT(*) FILTER (WHERE verified=TRUE)::int AS verified FROM evaluations`);console.log("Verification diagnostic:",JSON.stringify({reviews:reviews.rows[0],evaluations:evaluations.rows[0]}));}catch(error){console.error("Verification diagnostic failed:",error.message);}}
async function startServer(){if(store.mode()==="postgres"){try{const repaired=await store.syncApprovedReviews();if(repaired.verified>0)console.log(`[verification] restored ${repaired.verified} approved evaluation(s) to verified=true`);await logVerificationDiagnostic();}catch(error){console.error("[verification] startup sync failed:",error);}}app.listen(PORT,()=>console.log(`ModelJudge API running on http://localhost:${PORT} using ${store.mode()} storage`));}
if(require.main===module)startServer();
module.exports=app;
